### PR TITLE
change min zoom for generated tiles from 12 to 5

### PR DESCRIPTION
**Pull request by spatialhast**

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks for the PR @spatialhast !

I think this can be merged no problem, just wondering, what's the rationale for increasing the minimum tile level (what's the use case)?

**Comment by spatialhast** [comment]
@pierotofy I use WebODM for drone data processing and creating orthomosaic map tiles (TMS). These map tiles I use for adding into iHunter (https://www.ihunterapp.com/) web application. But this web application required map tiles from 6 zoom level (there is available validation map tiles).

**Comment by pierotofy** [comment]
Ah, very cool. Thanks for the explanation! :+1:

**Comment by spatialhast** [comment]
Hi @pierotofy ,
I updated WebODM (./webodm.sh update) with the latest version. After completing processing in 'orthophoto_tiles' and 'dsm_tiles' available map tiles from 5 to 21 zoom levels but on the map tiles from 5 to 12 zoom levels are unavailable ('detail: "Not found."' response). Can you please check this issue.
Thanks!

**Comment by pierotofy** [comment]
Latest WebODM version does not use tiles anymore, we have a dynamic tiler. See `tiler.py` in the WebODM repo.

**Pull request merged**
